win1xx2pytest

diff --git a/.github/workflows/test-windows.yml b/.github/workflows/test-windows.yml
--- a/.github/workflows/test-windows.yml
+++ b/.github/workflows/test-windows.yml
@@ -10,13 +10,13 @@ jobs:
       matrix:
         python-version: ["3.5"] #, "3.6", "3.7", "3.8", "pypy3"]
         architecture: ["x86", "x64"]
-        include:
-          - architecture: "x86"
-            platform-vcvars: "x86"
-            platform-msbuild: "Win32"
-          - architecture: "x64"
-            platform-vcvars: "x86_amd64"
-            platform-msbuild: "x64"
+        # include:
+        #   - architecture: "x86"
+        #     platform-vcvars: "x86"
+        #     platform-msbuild: "Win32"
+        #   - architecture: "x64"
+        #     platform-vcvars: "x86_amd64"
+        #     platform-msbuild: "x64"
         exclude:
           # PyPy does not support 64-bit on Windows
           - python-version: "pypy3"
@@ -64,7 +64,8 @@ jobs:
       run: python .github/workflows/system-info.py
 
     - name: pip install 
-      run: python -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' wheel pytest pytest-cov
+      run: | 
+        python -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' wheel pytest>5 pytest-cov
 
     - name: Prepare dependencies
       env:
@@ -166,77 +167,77 @@ jobs:
         name: ${{ steps.wheel.outputs.dist }}
         path: dist\*.whl
 
-  msys:
-    runs-on: windows-2019
+  # msys:
+  #   runs-on: windows-2019
 
-    strategy:
-      fail-fast: false
-      matrix:
-        mingw: ["MINGW32", "MINGW64"]
-        include:
-          - mingw: "MINGW32"
-            package: "mingw-w64-i686"
-          - mingw: "MINGW64"
-            package: "mingw-w64-x86_64"
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       mingw: ["MINGW32", "MINGW64"]
+  #       include:
+  #         - mingw: "MINGW32"
+  #           package: "mingw-w64-i686"
+  #         - mingw: "MINGW64"
+  #           package: "mingw-w64-x86_64"
 
-    defaults:
-      run:
-        shell: bash.exe --login -eo pipefail "{0}"
-    env:
-      MSYSTEM: ${{ matrix.mingw }}
-      CHERE_INVOKING: 1
+  #   defaults:
+  #     run:
+  #       shell: bash.exe --login -eo pipefail "{0}"
+  #   env:
+  #     MSYSTEM: ${{ matrix.mingw }}
+  #     CHERE_INVOKING: 1
 
-    timeout-minutes: 30
-    name: MSYS2 ${{ matrix.mingw }}
+  #   timeout-minutes: 30
+  #   name: MSYS2 ${{ matrix.mingw }}
 
-    steps:
-      - uses: actions/checkout@v2
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Set up shell
-        env:
-          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
-        run: echo ::add-path::C:\msys64\usr\bin\
-        shell: pwsh
+  #     - name: Set up shell
+  #       env:
+  #         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
+  #       run: echo ::add-path::C:\msys64\usr\bin\
+  #       shell: pwsh
 
-      - name: Install Dependencies
-        run: |
-          pacman -S --noconfirm \
-              ${{ matrix.package }}-python3-pip \
-              ${{ matrix.package }}-python3-setuptools \
-              ${{ matrix.package }}-python3-pytest \
-              ${{ matrix.package }}-python3-pytest-cov \
-              ${{ matrix.package }}-python3-cffi \
-              ${{ matrix.package }}-python3-olefile \
-              ${{ matrix.package }}-python3-numpy \
-              ${{ matrix.package }}-python3-pyqt5 \
-              ${{ matrix.package }}-python3-numpy \
-              ${{ matrix.package }}-freetype \
-              ${{ matrix.package }}-lcms2 \
-              ${{ matrix.package }}-libwebp \
-              ${{ matrix.package }}-libjpeg-turbo \
-              ${{ matrix.package }}-openjpeg2 \
-              ${{ matrix.package }}-libimagequant \
-              ${{ matrix.package }}-libraqm \
-              ${{ matrix.package }}-ghostscript \
-              subversion
+  #     - name: Install Dependencies
+  #       run: |
+  #         pacman -S --noconfirm \
+  #             ${{ matrix.package }}-python3-pip \
+  #             ${{ matrix.package }}-python3-setuptools \
+  #             ${{ matrix.package }}-python3-pytest \
+  #             ${{ matrix.package }}-python3-pytest-cov \
+  #             ${{ matrix.package }}-python3-cffi \
+  #             ${{ matrix.package }}-python3-olefile \
+  #             ${{ matrix.package }}-python3-numpy \
+  #             ${{ matrix.package }}-python3-pyqt5 \
+  #             ${{ matrix.package }}-python3-numpy \
+  #             ${{ matrix.package }}-freetype \
+  #             ${{ matrix.package }}-lcms2 \
+  #             ${{ matrix.package }}-libwebp \
+  #             ${{ matrix.package }}-libjpeg-turbo \
+  #             ${{ matrix.package }}-openjpeg2 \
+  #             ${{ matrix.package }}-libimagequant \
+  #             ${{ matrix.package }}-libraqm \
+  #             ${{ matrix.package }}-ghostscript \
+  #             subversion
 
-          python3 -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' pyroma
+  #         python3 -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' pyroma
 
-          pushd depends && ./install_extra_test_images.sh && popd
+  #         pushd depends && ./install_extra_test_images.sh && popd
 
-      - name: Build Pillow
-        run: |
-          # libtiff is unable to open files
-          CFLAGS="-coverage" python3 setup.py build_ext --disable-tiff install
+  #     - name: Build Pillow
+  #       run: |
+  #         # libtiff is unable to open files
+  #         CFLAGS="-coverage" python3 setup.py build_ext --disable-tiff install
 
-      - name: Test Pillow
-        run: |
-          python3 selftest.py --installed
-          python3 -m pytest -vx --cov PIL --cov Tests --cov-report term --cov-report xml Tests
+  #     - name: Test Pillow
+  #       run: |
+  #         python3 selftest.py --installed
+  #         python3 -m pytest -vx --cov PIL --cov Tests --cov-report term --cov-report xml Tests
 
-      - name: Upload coverage
-        run: |
-          python3 -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' codecov
-          bash <(curl -s https://codecov.io/bash) -F GHA_Windows
-        env:
-          CODECOV_NAME: MSYS2 ${{ matrix.mingw }}
+  #     - name: Upload coverage
+  #       run: |
+  #         python3 -m pip install --index-url 'https://:2020-06-30T10:43:17.228801Z@time-machines-pypi.sealsecurity.io/' codecov
+  #         bash <(curl -s https://codecov.io/bash) -F GHA_Windows
+  #       env:
+  #         CODECOV_NAME: MSYS2 ${{ matrix.mingw }}
